// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: src/models/session.proto

package models

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ProtoSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	UserAgent string `protobuf:"bytes,2,opt,name=UserAgent,proto3" json:"UserAgent,omitempty"`
	Created   int64  `protobuf:"varint,3,opt,name=Created,proto3" json:"Created,omitempty"`
	Token     string `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
	RefToken  string `protobuf:"bytes,5,opt,name=RefToken,proto3" json:"RefToken,omitempty"`
}

func (x *ProtoSession) Reset() {
	*x = ProtoSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_models_session_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoSession) ProtoMessage() {}

func (x *ProtoSession) ProtoReflect() protoreflect.Message {
	mi := &file_src_models_session_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoSession.ProtoReflect.Descriptor instead.
func (*ProtoSession) Descriptor() ([]byte, []int) {
	return file_src_models_session_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoSession) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ProtoSession) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ProtoSession) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ProtoSession) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ProtoSession) GetRefToken() string {
	if x != nil {
		return x.RefToken
	}
	return ""
}

type ProtoSessions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtoSessions []*ProtoSession `protobuf:"bytes,1,rep,name=ProtoSessions,proto3" json:"ProtoSessions,omitempty"`
}

func (x *ProtoSessions) Reset() {
	*x = ProtoSessions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_models_session_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoSessions) ProtoMessage() {}

func (x *ProtoSessions) ProtoReflect() protoreflect.Message {
	mi := &file_src_models_session_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoSessions.ProtoReflect.Descriptor instead.
func (*ProtoSessions) Descriptor() ([]byte, []int) {
	return file_src_models_session_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoSessions) GetProtoSessions() []*ProtoSession {
	if x != nil {
		return x.ProtoSessions
	}
	return nil
}

var File_src_models_session_proto protoreflect.FileDescriptor

var file_src_models_session_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x22, 0x96, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x55, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x52, 0x65, 0x66, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x52, 0x65, 0x66, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4b, 0x0a, 0x0d, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3a, 0x0a, 0x0d,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x73, 0x72, 0x63, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_models_session_proto_rawDescOnce sync.Once
	file_src_models_session_proto_rawDescData = file_src_models_session_proto_rawDesc
)

func file_src_models_session_proto_rawDescGZIP() []byte {
	file_src_models_session_proto_rawDescOnce.Do(func() {
		file_src_models_session_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_models_session_proto_rawDescData)
	})
	return file_src_models_session_proto_rawDescData
}

var file_src_models_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_models_session_proto_goTypes = []interface{}{
	(*ProtoSession)(nil),  // 0: models.ProtoSession
	(*ProtoSessions)(nil), // 1: models.ProtoSessions
}
var file_src_models_session_proto_depIdxs = []int32{
	0, // 0: models.ProtoSessions.ProtoSessions:type_name -> models.ProtoSession
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_models_session_proto_init() }
func file_src_models_session_proto_init() {
	if File_src_models_session_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_models_session_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_models_session_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoSessions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_models_session_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_models_session_proto_goTypes,
		DependencyIndexes: file_src_models_session_proto_depIdxs,
		MessageInfos:      file_src_models_session_proto_msgTypes,
	}.Build()
	File_src_models_session_proto = out.File
	file_src_models_session_proto_rawDesc = nil
	file_src_models_session_proto_goTypes = nil
	file_src_models_session_proto_depIdxs = nil
}
