// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: src/models/user.proto

package models

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Role int32

const (
	Role_Unknown   Role = 0
	Role_Creator   Role = 1
	Role_Admin     Role = 2
	Role_Moderator Role = 3
	Role_User      Role = 4
	Role_Guest     Role = 5
	Role_Friend    Role = 6
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "Unknown",
		1: "Creator",
		2: "Admin",
		3: "Moderator",
		4: "User",
		5: "Guest",
		6: "Friend",
	}
	Role_value = map[string]int32{
		"Unknown":   0,
		"Creator":   1,
		"Admin":     2,
		"Moderator": 3,
		"User":      4,
		"Guest":     5,
		"Friend":    6,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_src_models_user_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_src_models_user_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_src_models_user_proto_rawDescGZIP(), []int{0}
}

type ProtoUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey     string `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Nonce         string `protobuf:"bytes,3,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Description   string `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Birthday      int64  `protobuf:"varint,5,opt,name=Birthday,proto3" json:"Birthday,omitempty"` // unix time
	MinecraftName string `protobuf:"bytes,6,opt,name=MinecraftName,proto3" json:"MinecraftName,omitempty"`
	Role          Role   `protobuf:"varint,7,opt,name=Role,proto3,enum=models.Role" json:"Role,omitempty"`
	Created       int64  `protobuf:"varint,8,opt,name=Created,proto3" json:"Created,omitempty"` // unix time
	IsVIP         bool   `protobuf:"varint,9,opt,name=IsVIP,proto3" json:"IsVIP,omitempty"`
}

func (x *ProtoUser) Reset() {
	*x = ProtoUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_models_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoUser) ProtoMessage() {}

func (x *ProtoUser) ProtoReflect() protoreflect.Message {
	mi := &file_src_models_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoUser.ProtoReflect.Descriptor instead.
func (*ProtoUser) Descriptor() ([]byte, []int) {
	return file_src_models_user_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoUser) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ProtoUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtoUser) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ProtoUser) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProtoUser) GetBirthday() int64 {
	if x != nil {
		return x.Birthday
	}
	return 0
}

func (x *ProtoUser) GetMinecraftName() string {
	if x != nil {
		return x.MinecraftName
	}
	return ""
}

func (x *ProtoUser) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_Unknown
}

func (x *ProtoUser) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ProtoUser) GetIsVIP() bool {
	if x != nil {
		return x.IsVIP
	}
	return false
}

var File_src_models_user_proto protoreflect.FileDescriptor

var file_src_models_user_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22,
	0x89, 0x02, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x72, 0x74, 0x68,
	0x64, 0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x69, 0x72, 0x74, 0x68,
	0x64, 0x61, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x4d, 0x69, 0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x4d, 0x69, 0x6e, 0x65,
	0x63, 0x72, 0x61, 0x66, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x52, 0x6f, 0x6c,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x56, 0x49, 0x50, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x49, 0x73, 0x56, 0x49, 0x50, 0x2a, 0x5b, 0x0a, 0x04, 0x52,
	0x6f, 0x6c, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x6f, 0x64, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x10,
	0x04, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x75, 0x65, 0x73, 0x74, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x10, 0x06, 0x42, 0x0c, 0x5a, 0x0a, 0x73, 0x72, 0x63, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_models_user_proto_rawDescOnce sync.Once
	file_src_models_user_proto_rawDescData = file_src_models_user_proto_rawDesc
)

func file_src_models_user_proto_rawDescGZIP() []byte {
	file_src_models_user_proto_rawDescOnce.Do(func() {
		file_src_models_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_models_user_proto_rawDescData)
	})
	return file_src_models_user_proto_rawDescData
}

var file_src_models_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_models_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_src_models_user_proto_goTypes = []interface{}{
	(Role)(0),         // 0: models.Role
	(*ProtoUser)(nil), // 1: models.ProtoUser
}
var file_src_models_user_proto_depIdxs = []int32{
	0, // 0: models.ProtoUser.Role:type_name -> models.Role
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_models_user_proto_init() }
func file_src_models_user_proto_init() {
	if File_src_models_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_models_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_models_user_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_models_user_proto_goTypes,
		DependencyIndexes: file_src_models_user_proto_depIdxs,
		EnumInfos:         file_src_models_user_proto_enumTypes,
		MessageInfos:      file_src_models_user_proto_msgTypes,
	}.Build()
	File_src_models_user_proto = out.File
	file_src_models_user_proto_rawDesc = nil
	file_src_models_user_proto_goTypes = nil
	file_src_models_user_proto_depIdxs = nil
}
